defaults:
  flow:
    create_folds: True
    training: True
    testing: False


num_of_folds: 5

model:
  weight_path: weights/
  lr: 0.01

paths:
  data_path: data/audio/
  train_csv_path: data/train_metadata.csv
  test_csv_path: data/test_metadata.csv

class_names: [blues, classical, country, disco, hiphop, jazz, metal, pop, reggae, rock]

feature_extract: 
  sr: 44100
  n_fft: 1024
  hop_length: 512
  n_mels: 40
  