defaults:
  serialize_data: False
  training: True
  testing: False

folds:
  num_folds: 10
  fold_for_testing: 9
  train_folds: 5

model:
  weight_path: weights/
  lr: 0.01

paths:
  root_path: data/
  audio_path: data/audio/
  train_csv_path: data/train_metadata.csv
  test_csv_path: data/test_metadata.csv

class_names: [blues, classical, country, disco, hiphop, jazz, metal, pop, reggae, rock]

feature_extract: 
  sr: 44100
  n_fft: 1024
  hop_length: 512
  n_mels: 40
